version: '3.8'

services:
  ecoevents-server:
    build: .
    ports:
      - "4000:4000"
    volumes:
      # Montar volumen para persistir la base de datos SQLite
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Servicio opcional para desarrollo con PostgreSQL
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: ecoevents
  #     POSTGRES_USER: ecouser
  #     POSTGRES_PASSWORD: ecopass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
